
rvm: 
  - 1.8.7 # (current default)
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - ree

notifications:
  irc: "irc.freenode.org#flowof.info"
  recipients:
    - rob@flowof.info
